# Generated by Django 2.2 on 2019-10-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='creaded_on',
            new_name='created_on',
        ),
    ]
